### ISSUE TITLE
您好，可否优化移动端对菜单栏的显示呢？

### ISSUE THREAD

**Issue by handbye** [kuanghy/luring#1]
这个主题简直太棒了，当前移动端菜单栏是在顶部显示，可否参考[http://www.runoob.com/bootstrap/bootstrap-navbar.html](http://www.runoob.com/bootstrap/bootstrap-navbar.html)
中的“响应式的导航栏”。修改一下呢？谢谢啦，效果如下：
![image](https://user-images.githubusercontent.com/26617058/53230403-8f2a1a80-36c1-11e9-9b7b-8c7d03a72dee.png)

**Comment by kuanghy** [comment]
这个主题也是借用别人的，我只做了些简单的定制修改，个人对前端也不是太擅长，目前也比较忙，可能没时间优化。感兴趣的话可以自己尝试修改下 @handbye

**Comment by handbye** [comment]
@kuanghy 谢谢回复，我尝试下。

**Comment by kuanghy** [comment]
@handbye 你好，看着你用我的这个主题部署了网站 https://darkless.cn，但是没有修改百度统计的 js 脚本，我的百度统计账号记录了从你的网站过来的流量
